definitions:
  steps:
    - step: &build-test
        image: mcr.microsoft.com/dotnet/sdk:10.0
        caches:
          - dotnetcore
        script:
          - dotnet restore src/Dibk.Ftpb.Api.Email.sln
          - dotnet build-server shutdown
          - dotnet build src/Dibk.Ftpb.Api.Email.Web/Dibk.Ftpb.Api.Email.Web.csproj -c Release -f net10.0 --no-restore
          - dotnet publish src/Dibk.Ftpb.Api.Email.Web/Dibk.Ftpb.Api.Email.Web.csproj -c Release -f net10.0 -o publish --no-build -v detailed
        artifacts:
          - publish/**

pipelines:
  branches:
    master:
      - step: *build-test
      - step:
          name: Deploy to Octopus
          image: octopusdeploy/octo:6.17.3-alpine
          script:
            - export VERSION=2.0.$BITBUCKET_BUILD_NUMBER
            - octo pack --basePath=infrastructure --id $BITBUCKET_REPO_SLUG-infrastructure --version $VERSION --outFolder ./infra --format zip
            - octo push --package ./infra/$BITBUCKET_REPO_SLUG-infrastructure.$VERSION.zip  --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY
            - octo pack --basePath=publish --id $BITBUCKET_REPO_SLUG --version $VERSION --outFolder ./out --format zip
            - octo push --package ./out/$BITBUCKET_REPO_SLUG.$VERSION.zip  --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY

    feature/*:
      - step: *build-test
